### ISSUE TITLE
Absätze/Paragraphs

### ISSUE THREAD

**Issue by jdittrich** [freifunk/MoU#5]
**Deutsch** Der Text wurde mehrfach für seine mangelnde Lesbarkeit von Teilnehmern kritisiert. Eine einfache, inhaltsunabhängige Möglichkeit diese zu verbessern wäre das Einfügen von Absätzen – momentan ist unter den Überschriften fast immer ein durchgehender Textblock. 

---

**English:** The text has been criticized for lack of legibility by members. A simple content-agnostic way to improve  the situation is the use of paragraphs.

**Comment by tjanson** [comment]
Oh, I just fixed this in PR #7 (without seeing this issue). In the future, you can do this too ;-) (there’s an edit button)! It’s easier to implement changes when a Pull Request is available and ready to merge.

As for the paragraphs, I believe the author simply wasn’t aware of Markdown’s (sometimes annoying) habit of ignoring single line breaks.

**Comment by andibraeu** [comment]
it is merged
